### ISSUE TITLE
Update peer dependency material-ui

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ultimate-pagination/react-ultimate-pagination-material-ui#2]
Currently, their latest version is v0.17.1, maybe you could update it? I think there isn't any breaking changes...

**Comment by dmytroyarmak** [comment]
@DanielRamosAcosta Thank you, I've fixed it in v1.0.1

**Comment by DanielRamosAcosta** [comment]
Thanks!!

**Comment by verespej** [comment]
@dmytroyarmak Any chance of publishing to npm?

**Comment by dmytroyarmak** [comment]
@verespej Thank you. strange, I thought that I've published it. Will do it now...

**Comment by verespej** [comment]
Much appreciated!
